apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maguroskey
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tunamaguro/maguroskey-manifest.git
    path: apps
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"