apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: misskey-media-proxy-hpa
  namespace: maguroskey
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: misskey-media-proxy
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 150
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 120
