{
 "title": "Misskey Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inbound Traffic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{destination_workload=\"misskey-web\", destination_namespace=\"maguroskey\", source_namespace=\"cloudflare-tunnel\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Traffic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_to_world_total{source_namespace=\"maguroskey\", source_workload=\"misskey-web\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (kube_pod_container_status_ready{namespace=\"maguroskey\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Misskey Web Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" },
    { "expression": "$A / $C", "type": "math" },
    { "expression": "$D /$E", "type": "math" },
    { "expression": "$D / $F", "type": "math" }
   ]
  },
  {
   "title": "Misskey Postgres Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" },
    { "expression": "$A / $C", "type": "math" },
    { "expression": "$D /$E", "type": "math" },
    { "expression": "$D / $F", "type": "math" }
   ]
  },
  {
   "title": "Misskey Redis Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" },
    { "expression": "$A / $C", "type": "math" },
    { "expression": "$D /$E", "type": "math" },
    { "expression": "$D / $F", "type": "math" }
   ]
  },
  { "title": "Resources Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Web CPU Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"maguroskey\", container=\"misskey-web\"}[$__rate_interval]))",
     "legendFormat": "Real: {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_requests{namespace=\"maguroskey\", container=\"misskey-web\", resource=\"cpu\"})",
     "legendFormat": "Request: {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits{namespace=\"maguroskey\", container=\"misskey-web\", resource=\"cpu\"})",
     "legendFormat": "Limit: {{pod}}"
    }
   ]
  },
  {
   "title": "Web Memory Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"maguroskey\", container=\"misskey-web\"})",
     "legendFormat": "Real: {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_requests{namespace=\"maguroskey\", container=\"misskey-web\", resource=\"memory\"})",
     "legendFormat": "Request: {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits{namespace=\"maguroskey\", container=\"misskey-web\", resource=\"memory\"})",
     "legendFormat": "Limit: {{pod}}"
    }
   ]
  },
  {
   "title": "Postgres CPU Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"maguroskey\", container=\"postgres\"}[$__rate_interval]))",
     "legendFormat": "Real: {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_requests{namespace=\"maguroskey\", container=\"postgres\", resource=\"cpu\"})",
     "legendFormat": "Request: {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits{namespace=\"maguroskey\", container=\"postgres\", resource=\"cpu\"})",
     "legendFormat": "Limit: {{pod}}"
    }
   ]
  },
  {
   "title": "Postgres Memory Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"maguroskey\", container=\"postgres\"})",
     "legendFormat": "Real: {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_requests{namespace=\"maguroskey\", container=\"postgres\", resource=\"memory\"})",
     "legendFormat": "Request: {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits{namespace=\"maguroskey\", container=\"postgres\", resource=\"memory\"})",
     "legendFormat": "Limit: {{pod}}"
    }
   ]
  },
  {
   "title": "Redis CPU Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"maguroskey\", container=\"redis\"}[$__rate_interval]))",
     "legendFormat": "Real: {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_requests{namespace=\"maguroskey\", container=\"redis\", resource=\"cpu\"})",
     "legendFormat": "Request: {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits{namespace=\"maguroskey\", container=\"redis\", resource=\"cpu\"})",
     "legendFormat": "Limit: {{pod}}"
    }
   ]
  },
  {
   "title": "Redis Memory Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"maguroskey\", container=\"redis\"})",
     "legendFormat": "Real: {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_requests{namespace=\"maguroskey\", container=\"redis\", resource=\"memory\"})",
     "legendFormat": "Request: {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits{namespace=\"maguroskey\", container=\"redis\", resource=\"memory\"})",
     "legendFormat": "Limit: {{pod}}"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"maguroskey\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"maguroskey\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B /$A) *100", "type": "math" }
   ]
  },
  { "title": "Traffic Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Misskey Inbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(destination_workload) (rate(hubble_flows_processed_total{source_namespace=\"cloudflare-tunnel\", destination_namespace=\"maguroskey\", destination_workload=\"misskey-web\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(source_workload) (rate(hubble_flows_to_world_total{source_namespace=\"maguroskey\", source_workload=\"misskey-web\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Misskey to Postgres Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(source_workload) (rate(hubble_flows_processed_total{source_namespace=\"maguroskey\", destination_namespace=\"maguroskey\", source_workload=\"misskey-web\", destination_workload!~\"redis\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Misskey to Redis Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(destination_workload) (rate(hubble_flows_processed_total{source_namespace=\"maguroskey\", destination_workload=\"redis\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{namespace=\"maguroskey\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Transmited",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{namespace=\"maguroskey\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}