apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maguroskey-cnpg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cloudnative-pg/charts.git
    path: charts/cloudnative-pg
    targetRevision: cloudnative-pg-v0.21.4
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnpg-system
  syncPolicy:     
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true