apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maguroskey-dashboard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tunamaguro/maguroskey-manifest.git
    path: metrics
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    automated:
      prune: true