apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maguroskey-misskey
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tunamaguro/maguroskey-manifest.git
    path: misskey
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: maguroskey
  syncPolicy:
    syncOptions:
      - CreateNamespace=true