apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: misskey-postgres
  namespace: maguroskey
spec:
  description: "datbase for Misskey"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3-4
  instances: 3
  primaryUpdateStrategy: unsupervised
  superuserSecret:
    name: db-superuser
  bootstrap:
    initdb:
      database: misskey
      owner: misskey
      secret:
        name: db-misskey-user

  minSyncReplicas: 1
  maxSyncReplicas: 1
  backup:
    barmanObjectStore:
      destinationPath: s3://misskey-backup/backups
      endpointURL: https://2b49b33bf6d3b47966f0d6bc3c6a1130.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: backup-key
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-key
          key: ACCESS_SECRET_KEY
      # wal:
      #   compression: bzip2
      #   maxParallel: 8
      data:
        compression: bzip2
    retentionPolicy: "5d"
  
  storage:
    storageClass: local-path
    size: 10Gi
  resources:
    requests:
      memory: "1.2Gi"
      cpu: "250m"
    limits:
      memory: "1.5Gi"
      cpu: "400m"
