apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: misskey-postgres
  namespace: maguroskey
spec:
  description: "datbase for Misskey"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3-4
  instances: 2
  primaryUpdateStrategy: unsupervised
  superuserSecret:
    name: db-superuser
  bootstrap:
    initdb:
      database: misskey
      owner: misskey
      secret:
        name: db-misskey-user
    # recovery:
    #   backup:
    #     name: maguroskey-scheduled-backup-20240715000000

  backup:
    barmanObjectStore:
      destinationPath: s3://misskey-backup/backups
      endpointURL: https://2b49b33bf6d3b47966f0d6bc3c6a1130.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: backup-key
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-key
          key: ACCESS_SECRET_KEY
      # wal:
      #   compression: bzip2
      #   maxParallel: 8
      data:
        compression: bzip2
        jobs: 8
    retentionPolicy: "3d"
  
  storage:
    storageClass: local-path
    size: 10Gi
  resources:
    requests:
      memory: 0.8Gi
      cpu: 100m
    limits:
      memory: 1.0Gi
      cpu: 300m
