apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: maguroskey-auth
  namespace: maguroskey
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: read-maguroskey
    serviceAccount: default