apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-misskey-user-secret
  namespace: maguroskey
spec:
  type: kv-v2
  mount: kv
  path: maguroskey/db-misskey-user
  destination:
    name: db-misskey-user
    create: true
    overwrite: false
    type: kubernetes.io/basic-auth
  refreshAfter: 30s
  vaultAuthRef: maguroskey-auth

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-super-user-secret
  namespace: maguroskey
spec:
  type: kv-v2
  mount: kv
  path: maguroskey/db-super-user
  destination:
    name: db-super-user
    create: true
    overwrite: false
    type: kubernetes.io/basic-auth
  refreshAfter: 30s
  vaultAuthRef: maguroskey-auth

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: maguroskey-config-secret
  namespace: maguroskey
spec:
  type: kv-v2
  mount: kv
  path: maguroskey/config
  destination:
    name: maguroskey-config
    create: true
    overwrite: false
  refreshAfter: 30s
  vaultAuthRef: maguroskey-auth

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: maguroskey-backup-secret
  namespace: maguroskey
spec:
  type: kv-v2
  mount: kv
  path: maguroskey/backup-key
  destination:
    name: backup-key
    create: true
    overwrite: false
  refreshAfter: 30s
  vaultAuthRef: maguroskey-auth