apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: maguroskey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: ceph-rbd