---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: maguroskey
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2.4-alpine
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
      #     volumeMounts:
      #       - name: redis-data
      #         mountPath: /data
      # volumes:
      #   - name: redis-data
      #     persistentVolumeClaim:
      #       claimName: redis-data
