---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: maguroskey
spec:
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: redis